import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import GraphQlProvider from "@/lib/gqlProvider"; 
const inter = Inter({ subsets: ["latin"] });
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <GraphQlProvider>{children}</GraphQlProvider>
      </body>
    </html>
  );
}
